server:
  port: 8001
spring:
  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8761/eureka
  instance:
    prefer-ip-address: true   #使用ip作为host
name:
  xincm
evn:
  prd
